-- Historical migration baseline: 20260504014314 exercise_library_complete_v2.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
