-- Historical migration baseline: 20260509113515 coach_hidden_workouts_2026_05_08.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
