-- Historical migration baseline: 20260503162954 wave2_security_definer_views_fix.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
