-- Historical migration baseline: 20260503163656 wave2_rls_auth_uid_initplan_fix.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
