-- Historical migration baseline: 20260508015325 fix_manage_workout_session_timezone_2026_05_07.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
