-- Historical migration baseline: 20260509113224 fix_student_reads_own_coach_2026_05_08.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
