-- Historical migration baseline: 20260503161717 c05_inadimplencia_rls_sessions_set_logs.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
