-- Historical migration baseline: 20260503163753 wave2_revoke_anon_from_all_security_definer_fns.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
