-- Historical migration baseline: 20260503162654 wave2_must_reset_password_delete_account_indexes.
-- This version was already applied in the production Supabase project before
-- the repository received the complete migration history. It is intentionally
-- a no-op so preview branches can reconcile the existing production history.
