-- Treinova - expansão da biblioteca de exercícios por grupo muscular
-- Data: 2026-05-08
-- Fontes de taxonomia/organização consultadas: ACE Exercise Library, ExRx Exercise Directory e NASM Exercise Library.
-- Objetivo: ampliar a biblioteca do professor e garantir imagem realista padrão para todos os exercícios, sem gravar séries/reps/pausa no exercício.

begin;

with seed(name, cat, muscle_group, method, observations) as (
values
  ('Ab Wheel (Roda Abdominal)', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Ab wheel (rolinho abdominal)', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Abdominal canivete', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Abdominal infra (elevação de pernas)', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Abdominal Infra na Barra', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Abdominal supra (crunch)', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Bear crawl', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Bicicleta abdominal', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Crunch Abdominal', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Crunch na máquina', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Crunch na polia alta', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Crunch Oblíquo', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Dead bug', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Dead bug com bola', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Elevação de joelhos na barra', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Elevação de Pernas Deitado', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Elevação de pernas na paralela', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Farmer carry unilateral', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Flexão de quadril na paralela com joelho estendido', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Hollow hold', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Hollow rock', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Levantamento Terra', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Mountain climber', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Pallof press', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Pallof press ajoelhado', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha (Plank)', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha com elevação alternada de pernas', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha com toque no ombro', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha isométrica', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha isométrica + Abdominal supra 90°', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha isométrica + Super-man no solo', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha lateral', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha lateral com abdução', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Prancha lateral com rotação', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Reverse crunch', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Russian Twist', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Russian twist com peso', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Sit-up no banco declinado', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Toes to bar', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Vácuo abdominal', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Woodchopper no cabo', 'core', 'Abdômen', 'Core', 'Imagem realista padrão incluída no app.'),
  ('Air bike', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Battle rope waves', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Bike Ergométrica', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Bike ergométrica steady state', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Bike intervalada', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Bike sprint 30 segundos', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Bike Zona 2/3', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Burpees', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Caminhada ao ar livre', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Caminhada inclinada', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Corda (Jump Rope)', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Corda jump rope', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Corrida intervalada ao ar livre', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Corrida leve ao ar livre', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Corrida na esteira', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Elíptico', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Elíptico intervalado', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Escada (Step)', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Escada ergométrica', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Escada step machine', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Esteira intervalada', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Esteira subida leve', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Esteira tiro curto', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('High knees', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('HIIT na esteira', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Jumping jacks', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Mountain climber rápido', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Polichinelo', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Remo ergométrico', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Remo intervalado', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Shuttle run', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Ski erg', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Spinning', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Spinning bike intervalado', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Step-up aeróbio', 'cardio', 'Aeróbio', 'Condicionamento', 'Imagem realista padrão incluída no app.'),
  ('Chin-up supinado', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca 21', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca 21 com barra W', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Alternada com Halter', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca alternada com halteres', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca alternada sentado', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Bayesian no cabo', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca cabo barra W', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Concentrada', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca concentrada com halter', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca concentrada no banco inclinado', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca direta barra W', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca direta com barra', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca direta na polia baixa', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca direta no cabo', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Inclinada com Halter', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca inclinada com halteres', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Inversa', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca inversa com barra', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca inversa na polia', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca máquina unilateral', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca martelo', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca martelo alternada', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca martelo no cabo com corda', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca no Cabo com Barra W', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca no TRX', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca punho pronada', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca punho supinada', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Scott (Preacher Curl)', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Scott com halter', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca scott na máquina', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Scott unilateral', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca spider', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca spider com barra W', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rosca Zottman', 'biceps', 'Bíceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra Fixa (Pullup)', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra fixa assistida', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra fixa pegada neutra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra fixa pegada pronada', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra fixa pegada supinada', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Barra fixa supinada + Pulldown com corda', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Face pull sentado', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Good morning leve para lombar', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hiperextensão Lombar', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hiperextensão lombar no banco', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Levantamento terra convencional', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Meadows row', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pull over com halter', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pulldown braços retos', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pulldown com corda', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pulley Costas (Triângulo)', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pulley Frente (Pegada Aberta)', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pullover máquina', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pullover no cabo com corda', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada com Barra Pronada', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada com triângulo (pegada neutra)', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada frontal com barra (pegada neutra)', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada frontal pegada aberta', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada frontal pegada neutra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada neutra no pulley', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada supinada no pulley', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Puxada unilateral no cabo', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rack pull', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada alta com barra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada Alta no Cabo', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada baixa com triângulo', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada baixa pegada neutra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada baixa unilateral', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada Cavalinho', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada cavalinho com apoio no peito', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada cavalinho livre com triângulo', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada curvada com barra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada curvada com halter unilateral', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada curvada pegada supinada', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada invertida na barra', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada invertida no TRX', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada máquina alta', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada máquina articulada', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada no Cabo Sentado', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada Unilateral com Halter', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Serrote com Halter', 'back', 'Costas', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abdução de Quadril com Elástico', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abdução de quadril na máquina', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abdução de quadril na polia', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abdução de quadril no cabo', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abdução lateral deitado', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo reverso foco glúteos', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento sumô com halter', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cable hip abduction', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Caminhada lateral com miniband', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Coice no Smith', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Donkey Kicks', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Donkey kicks no solo', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação pélvica com barra', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação Pélvica no Solo', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação pélvica unilateral', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Extensão de quadril no banco romano', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Frog pump', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Glúteo na máquina', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Glúteo no Cabo (Kickback)', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Glúteo quatro apoios com caneleira', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Glúteo quatro apoios no cabo', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hip Thrust', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hip thrust com barra', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hip thrust máquina', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hip thrust unilateral', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Kickback máquina', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Kickback no cabo extensão de quadril', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mesa Hip Thrust (máquina)', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Monster walk com miniband', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Passada Lateral', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Passada lateral com elástico', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Ponte de glúteos com miniband', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Ponte unilateral de glúteos', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pull through foco glúteos', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Step-up alto foco glúteos', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Sumô deadlift descalço', 'glute', 'Glúteos', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Abertura de quadril 90 90', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Abertura de Quadril 90/90', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Adductor rockback', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento borboleta', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento couch stretch', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento de Isquiotibiais', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento de panturrilha na parede', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento de Quadríceps', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento dorsal no banco', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento flexor de quadril ajoelhado', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento gato-camelo', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento peitoral na parede', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento piriforme deitado', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Alongamento posterior com faixa', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Cadeira adutora + Cadeira abdutora 90°', 'adductor', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('CARs de ombro', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('CARs de quadril', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Cat-Cow (Mobilidade Lombar)', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Cossack squat mobilidade', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Deep squat com rotação', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Deep squat passivo', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Dislocação de Ombros (bastão)', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Frog Stretch', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Hip Circles', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade cervical controlada', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de adutores frog', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de adutores frog no solo', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de posteriores (unilateral)', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de posteriores no solo (unilateral)', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de punho', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de quadril 90/90 com troca', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de Tornozelo', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade de tornozelo joelho na parede', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade rotacional de ombros', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade rotacional de ombros com bastão ou corda', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade rotacional de tronco na parede', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Mobilidade torácica em quatro apoios', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Pigeon Pose', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Pigeon pose abertura de quadril', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Rotação Torácica', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Rotação torácica no solo', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Scorpion Stretch', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Thread the needle', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('World greatest stretch', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('World greatest stretch com rotação', 'mobility', 'Mobilidade', 'Mobilidade', 'Imagem realista padrão incluída no app.'),
  ('Arnold press', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo inverso com halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo inverso na máquina', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo inverso no cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento Arnold', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento articulado', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento articulado + Elevação lateral c/ halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento com Barra', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento com halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento militar com barra', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento militar em pé', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento na máquina', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento no Smith', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Desenvolvimento unilateral com halter', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação frontal com barra', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação Frontal com Halter', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação frontal com halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação frontal no cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral com cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação Lateral com Halter', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral com halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral inclinada', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral máquina', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação Lateral no Cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral sentado', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação lateral unilateral no cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Encolhimento com Barra', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Encolhimento com Halteres', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Encolhimento de ombros (shrug)', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Face pull (com duas cordas)', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Face pull no cabo', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Press Arnold sentado', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Push press', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Remada alta no Smith', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rotação cubana com halteres em pé', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rotação externa com elástico', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Rotação interna com elástico', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Scaption raise', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Wall slide', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Y raise inclinado', 'shoulder', 'Ombros', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento na ponta dos pés', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Elevação de ponta dos pés sentado', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Farmer walk na ponta dos pés', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Leg Press (foco panturrilha)', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha bilateral no degrau', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha com joelho estendido', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha com joelho flexionado', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha donkey', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha em pé com halteres', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha em pé na máquina', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha em pé no Smith', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha isométrica no topo', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha Livre (Bilateral)', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha na máquina horizontal', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no cabo', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no hack', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no leg horizontal', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no leg press', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no leg press 45°', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no leg press horizontal', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha no Smith', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha sentado', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha sentado unilateral', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha tibial anterior', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha Unilateral', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha unilateral livre', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilha unilateral no degrau', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilhas no leg horizontal', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Panturrilhas no Smith', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pogo jumps', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Saltos no step baixo', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tibialis raise na parede', 'calf', 'Panturrilha', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Chest press sentado', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover na polia alta', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover no Cabo', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover no cabo (cruzamento)', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover polia alta', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover polia baixa', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crossover polia média', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo declinado com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo Inclinado', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo inclinado com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo na máquina unilateral', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo no banco plano', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo no cross over polia baixa, banco inclinado 45°', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Crucifixo Reto', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão com pegada aberta', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão de braço', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão de Braços', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão de braços fechada', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão diamante', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão Inclinada (pés altos)', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão no TRX', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão pliométrica', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Floor press com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Paralela com foco em peito', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Peck deck', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Peck Deck (Fly na Máquina)', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pullover com Halter', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pullover no cabo', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Squeeze press com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino com pegada neutra', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino Declinado com Barra', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino declinado com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino inclinado com barra', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino inclinado com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino inclinado com halteres (banco 30°)', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino inclinado máquina convergente', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino máquina convergente', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino no Smith', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino reto articulado', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino reto com barra', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino reto com halteres', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino unilateral com halter', 'chest', 'Peito', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Back extension foco posterior', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Bom dia (good morning)', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cadeira flexora', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cadeira flexora unilateral', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão Nórdica (Nordic Curl)', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão nórdica nordic curl', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexora deitado', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexora no cabo', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexora sentado', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexora unilateral em pé', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Glute ham raise', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Good Morning', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Good morning com barra', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hamstring curl na bola suíça', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hamstring walkout', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Kettlebell swing', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Levantamento terra com trap bar', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Levantamento Terra Romeno', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Levantamento terra sumô', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mesa flexora', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mesa flexora leg curl', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mesa flexora unilateral', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Nordic curl assistido', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Ponte de posterior no slider', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Pull through no cabo', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('RDL (stiff) com barra descalço', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('RDL com barra descalço', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('RDL com halteres', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('RDL unilateral', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Stiff (Terra Romeno)', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Stiff com barra', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Stiff com halteres', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Stiff unilateral com halter', 'hamstring', 'Posterior', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo (lunge)', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo caminhando', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo lateral', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo no Smith', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Afundo reverso', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Búlgaro', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento búlgaro descalço', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento búlgaro split squat', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento caixa', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento frontal', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Goblet', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento goblet com halter', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento hack linear', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento livre com barra', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento no Smith', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento pausado', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Smith', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento split búlgaro com halteres', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Sumô', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Sumô Profundo', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Agachamento Zercher', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Avanço com Barra', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Avanço com Halteres', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Avanço com halteres lunge', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cadeira extensora', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cadeira extensora com pausa', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Cadeira extensora unilateral', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Goblet squat com calcanhar elevado', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hack Squat', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Hack squat máquina', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Leg press 45°', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Leg press horizontal', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Leg press unilateral', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Sissy squat', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Spanish squat', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Step-up com halteres', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Step-up no banco', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Wall sit', 'quad', 'Quadríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Extensão de tríceps máquina', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Extensão Tate press', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão diamante para tríceps', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Flexão fechada', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('JM press', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Kickback no cabo', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mergulho em Paralelas (Dips)', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Mergulho em paralelas dips', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Paralela assistida para tríceps', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino Fechado', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino fechado com barra', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Supino fechado no Smith', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps coice bilateral', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps coice com halter', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps corda acima da cabeça', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps corda ajoelhado', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps Corda no Cabo', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps cross unilateral', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps francês com barra W', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps francês com corda', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps francês com corda na polia média', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps Francês com Halter', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps francês sentado com halter', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps francês unilateral', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps mergulho no banco', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps Pulley com Barra', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps pulley com barra W', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps pulley pegada reversa', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps Testa (Skullcrusher)', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps testa com barra skullcrusher', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps testa com barra W', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps testa com halteres', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps testa na polia baixa', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps Testa no Cabo', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.'),
  ('Tríceps unilateral no cabo', 'triceps', 'Tríceps', 'Séries múltiplas', 'Imagem realista padrão incluída no app.')
)
insert into public.exercises
  (workout_id, student_id, position, name, cat, muscle_group, sets_count, reps, pause, cadence, method, observations, is_library, image_url)
select
  null,
  null,
  0,
  s.name,
  s.cat,
  s.muscle_group,
  1,
  'Seguir período',
  'Seguir período',
  '',
  s.method,
  s.observations,
  true,
  null
from seed s
where not exists (
  select 1
  from public.exercises e
  where e.is_library = true
    and lower(e.name) = lower(s.name)
);

update public.exercises
set
  sets_count = 1,
  reps = 'Seguir período',
  pause = 'Seguir período',
  observations = coalesce(nullif(observations, ''), 'Imagem realista padrão incluída no app.')
where is_library = true;

update public.exercises
set muscle_group = case
  when lower(muscle_group) in ('peito') then 'Peito'
  when lower(muscle_group) in ('costas') then 'Costas'
  when lower(muscle_group) in ('ombro', 'ombros') then 'Ombros'
  when lower(muscle_group) in ('biceps', 'bíceps') then 'Bíceps'
  when lower(muscle_group) in ('triceps', 'tríceps') then 'Tríceps'
  when lower(muscle_group) in ('quadriceps', 'quadríceps') then 'Quadríceps'
  when lower(muscle_group) in ('posterior') then 'Posterior'
  when lower(muscle_group) in ('gluteo', 'glúteo', 'gluteos', 'glúteos') then 'Glúteos'
  when lower(muscle_group) in ('panturrilha') then 'Panturrilha'
  when lower(muscle_group) in ('abdomen', 'abdômen') then 'Abdômen'
  when lower(muscle_group) in ('mobilidade') then 'Mobilidade'
  when lower(muscle_group) in ('aerobio', 'aeróbio') then 'Aeróbio'
  else muscle_group
end
where is_library = true;

commit;
